import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen w-full bg-yellow-100">
        <Sidebar />

        {/* For Body Section */}
        <div className="flex flex-col w-full h-full ml-64 p-4 mt-6">
        {children}

        </div>
        
        </div>

        </body>
        
    </html>
  );
}
